development: &default
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: 5
  username: postgres
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: hound_test
